# Generated by Django 5.1.1 on 2024-09-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = []
