# Generated by Django 5.1.1 on 2024-10-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=models.CharField(
                choices=[
                    ("IE", "Individual Entrepreneur"),
                    ("LLC", "Limited Liability Company"),
                    ("JSC", "Joint-Stock Company"),
                ],
                default="LLC",
                max_length=10,
            ),
        ),
    ]
