# Generated by Django 5.1.1 on 2024-09-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0004_tender_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
