# Generated by Django 5.1.1 on 2024-09-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0005_alter_employee_id_alter_organization_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="organizationresponsible",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tender",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
